name:                delta
version:             0.1.0.0
github:              "alpha-convert/delta"
license:             BSD-3-Clause
author:              "Joseph W. Cutler"
maintainer:          "jwc@seas.upenn.edu"
copyright:           "2023"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alpha-convert/delta#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- parsec
- array
- HUnit
- monad-loops
- dunai
- QuickCheck
- MonadRandom

ghc-options:
- -Wall
- -Werror=incomplete-patterns
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists
- -Wno-unused-imports
- -Wno-unused-top-binds
- -Wno-missing-signatures

library:
  source-dirs: src

executables:
  stream-types2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delta

tests:
  stream-types2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delta
